# Generated by Django 5.2.17 on 2026-09-27 20:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ruc",
                    models.CharField(max_length=13, unique=True, verbose_name="RUC"),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Razón social"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PUBLICA", "Pública"),
                            ("PRIVADA", "Privada"),
                            ("ONG", "ONG / Otra"),
                        ],
                        default="PRIVADA",
                        max_length=20,
                    ),
                ),
                ("direccion", models.CharField(blank=True, max_length=250)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                (
                    "correo",
                    models.EmailField(
                        help_text="Correo al que se envían las cartas de aceptación.",
                        max_length=254,
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="InformeFinal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resumen", models.TextField(verbose_name="Resumen ejecutivo")),
                ("actividades_realizadas", models.TextField()),
                (
                    "resultados",
                    models.TextField(verbose_name="Resultados y aprendizajes"),
                ),
                (
                    "conclusiones",
                    models.TextField(verbose_name="Conclusiones y recomendaciones"),
                ),
                ("horas_cumplidas", models.PositiveIntegerField()),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        upload_to="informes/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "doc", "docx"]
                            )
                        ],
                        verbose_name="Informe (PDF/Word)",
                    ),
                ),
                (
                    "certificado_empresa",
                    models.FileField(
                        blank=True,
                        upload_to="certificados_empresa/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                        verbose_name="Certificado de culminación emitido por la empresa (PDF)",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "En revisión"),
                            ("CORRECCION", "Con observaciones"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                    ),
                ),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlanPracticas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objetivo_general", models.TextField()),
                ("objetivos_especificos", models.TextField()),
                (
                    "actividades",
                    models.TextField(verbose_name="Actividades a desarrollar"),
                ),
                ("cronograma", models.TextField(help_text="Semana por semana.")),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        upload_to="planes/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "doc", "docx"]
                            )
                        ],
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "En revisión"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrador"),
                            ("COORDINADOR", "Docente-coordinador"),
                            ("TUTOR", "Docente-tutor"),
                            ("ESTUDIANTE", "Estudiante"),
                            ("RECTOR", "Rector"),
                        ],
                        default="ESTUDIANTE",
                        max_length=20,
                    ),
                ),
                ("cedula", models.CharField(blank=True, max_length=13)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("semestre", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=150)),
                (
                    "practicas_requeridas",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="Número de prácticas que el estudiante debe culminar para graduarse.",
                    ),
                ),
                ("horas_por_practica", models.PositiveIntegerField(default=240)),
                (
                    "tutores",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"rol": "TUTOR"},
                        related_name="carreras_tutoria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="usuario",
            name="carrera",
            field=models.ForeignKey(
                blank=True,
                help_text="Carrera del estudiante (o del coordinador).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios",
                to="practicas.carrera",
            ),
        ),
        migrations.CreateModel(
            name="Convenio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=30, unique=True)),
                (
                    "objeto",
                    models.TextField(blank=True, verbose_name="Objeto del convenio"),
                ),
                ("cupos", models.PositiveIntegerField(default=5)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "documento",
                    models.FileField(
                        blank=True,
                        upload_to="convenios/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "rep_legal_nombre",
                    models.CharField(
                        max_length=150, verbose_name="Representante legal"
                    ),
                ),
                (
                    "rep_legal_cedula",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        verbose_name="Cédula del representante",
                    ),
                ),
                (
                    "rep_legal_cargo",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Cargo del representante",
                    ),
                ),
                (
                    "tutor_emp_nombre",
                    models.CharField(max_length=150, verbose_name="Tutor empresarial"),
                ),
                (
                    "tutor_emp_cargo",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Cargo del tutor empresarial",
                    ),
                ),
                (
                    "tutor_emp_correo",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="Correo del tutor empresarial",
                    ),
                ),
                (
                    "tutor_emp_telefono",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Teléfono del tutor empresarial",
                    ),
                ),
                (
                    "carreras",
                    models.ManyToManyField(
                        related_name="convenios", to="practicas.carrera"
                    ),
                ),
                (
                    "tutores",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"rol": "TUTOR"},
                        related_name="convenios_tutoria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="convenios",
                        to="practicas.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="ObservacionInforme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField(verbose_name="Corrección solicitada")),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("atendida", models.BooleanField(default=False)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "informe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observaciones",
                        to="practicas.informefinal",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="ComentarioPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="practicas.planpracticas",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha"],
            },
        ),
        migrations.CreateModel(
            name="Solicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_practica",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="N.º de práctica"
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        max_length=150, verbose_name="Área / departamento"
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(verbose_name="Fecha de inicio propuesta"),
                ),
                ("fecha_fin", models.DateField(verbose_name="Fecha de fin propuesta")),
                ("horas", models.PositiveIntegerField(default=240)),
                ("motivo", models.TextField(verbose_name="Justificación")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                            ("DEVUELTO", "Devuelto"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                    ),
                ),
                (
                    "observacion",
                    models.TextField(
                        blank=True, verbose_name="Observación del coordinador"
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "convenio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes",
                        to="practicas.convenio",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"rol": "TUTOR"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_tutor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creado"],
            },
        ),
        migrations.AddField(
            model_name="planpracticas",
            name="solicitud",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan",
                to="practicas.solicitud",
            ),
        ),
        migrations.AddField(
            model_name="informefinal",
            name="solicitud",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="informe",
                to="practicas.solicitud",
            ),
        ),
        migrations.CreateModel(
            name="CartaAceptacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=30, unique=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("POR_FIRMAR", "Por firmar"),
                            ("FIRMADA", "Firmada"),
                            ("ENVIADA", "Enviada a la empresa"),
                        ],
                        default="POR_FIRMAR",
                        max_length=15,
                    ),
                ),
                (
                    "archivo_firmado",
                    models.FileField(
                        blank=True,
                        upload_to="cartas/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                    ),
                ),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                ("enviada_a", models.EmailField(blank=True, max_length=254)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "solicitud",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carta",
                        to="practicas.solicitud",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("APROBACION", "Certificado de aprobación de prácticas"),
                            ("CULMINACION", "Certificado de culminación de prácticas"),
                            (
                                "FINAL",
                                "Certificado final de prácticas preprofesionales",
                            ),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "codigo",
                    models.CharField(editable=False, max_length=40, unique=True),
                ),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "emitido_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificados_emitidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificados",
                        to="practicas.solicitud",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tipo", "solicitud"), name="un_cert_por_tipo_y_practica"
                    )
                ],
            },
        ),
    ]
