# Generated by Django 5.2.17 on 2026-09-27 23:18

import django.db.models.deletion
import practicas.validadores
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practicas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="semestre",
        ),
        migrations.AddField(
            model_name="usuario",
            name="debe_cambiar_clave",
            field=models.BooleanField(
                default=False,
                help_text="Obliga a cambiar la contraseña en el próximo ingreso.",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="carrera",
            field=models.ForeignKey(
                blank=True,
                help_text="Carrera del estudiante, tutor o coordinador.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios",
                to="practicas.carrera",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="cedula",
            field=models.CharField(
                blank=True,
                max_length=10,
                validators=[practicas.validadores.validar_cedula],
                verbose_name="Cédula",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, verbose_name="Teléfono"),
        ),
    ]
