# Generated by Django 5.2.17 on 2026-09-28 00:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practicas", "0002_cedula_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="convenio",
            name="tutor_emp_cargo",
        ),
        migrations.RemoveField(
            model_name="convenio",
            name="tutor_emp_correo",
        ),
        migrations.RemoveField(
            model_name="convenio",
            name="tutor_emp_nombre",
        ),
        migrations.RemoveField(
            model_name="convenio",
            name="tutor_emp_telefono",
        ),
        migrations.AddField(
            model_name="cartaaceptacion",
            name="archivo_aceptacion",
            field=models.FileField(
                blank=True,
                help_text="Si no se adjunta, se usa la carta generada por el sistema.",
                upload_to="cartas_aceptacion/",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
                verbose_name="Carta de aceptación firmada (PDF, opcional)",
            ),
        ),
        migrations.AddField(
            model_name="cartaaceptacion",
            name="fecha_respuesta",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cartaaceptacion",
            name="horario",
            field=models.CharField(
                blank=True,
                help_text="Ej.: Lunes a viernes de 08:00 a 13:00",
                max_length=120,
                verbose_name="Horario de prácticas",
            ),
        ),
        migrations.AddField(
            model_name="cartaaceptacion",
            name="observacion_empresa",
            field=models.TextField(blank=True, verbose_name="Observación"),
        ),
        migrations.AddField(
            model_name="cartaaceptacion",
            name="respondida_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cartas_respondidas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="convenio",
            name="tutor_empresarial",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"rol": "TUTOR_EMP"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="convenios_empresa",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="cargo",
            field=models.CharField(
                blank=True,
                help_text="Cargo en la empresa (tutor empresarial).",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                help_text="Solo para tutores empresariales.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutores_empresariales",
                to="practicas.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="cartaaceptacion",
            name="archivo_firmado",
            field=models.FileField(
                blank=True,
                upload_to="cartas/",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
                verbose_name="Solicitud firmada (PDF)",
            ),
        ),
        migrations.AlterField(
            model_name="cartaaceptacion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("POR_FIRMAR", "Por firmar (Rector)"),
                    ("FIRMADA", "Firmada, por enviar"),
                    ("ENVIADA", "Enviada al tutor empresarial"),
                    ("ACEPTADA", "Aceptada por la empresa"),
                    ("NO_ACEPTADA", "No aceptada por la empresa"),
                ],
                default="POR_FIRMAR",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("COORDINADOR", "Docente-coordinador"),
                    ("TUTOR", "Docente-tutor"),
                    ("ESTUDIANTE", "Estudiante"),
                    ("RECTOR", "Rector"),
                    ("TUTOR_EMP", "Tutor empresarial"),
                ],
                default="ESTUDIANTE",
                max_length=20,
            ),
        ),
    ]
